always_pending:
    title_regex: '(WIP|wip)'
    labels:
        - wip
    explanation: 'This PR is a work in progress...'
approve_by_comment: true
approve_regex: '^(Approved|:shipit:|:\+1:)'
author_approval: ignored
reject_regex: '^(Rejected|:-1:)'
reset_on_push: true
reset_on_reopened: true
reviewers:
  name: autobots
  required: 1
  members:
  - GypsyBojangles
  - smclauch
  - snayler0
  - alicelee999
  - ga-autobots
  - aynsof
  - TheAngeloPace
  - jmettes
  conditions:
    branches:
      - integration
      - master
